development:
  adapter: postgresql
  encoding: unicode
  database: wallstickers_development
  pool: 5
  username: wallstickers
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: wallstickers_test
  pool: 5
  username: wallstickers
  password:
